# Nixpacks configuration for Railway

[phases.setup]
nixPkgs = ["zlib", "libjpeg", "libpng", "libwebp"]

[phases.build]
cmds = ["cd generative_art_website_project && python manage.py collectstatic --noinput"]

[start]
cmd = "cd generative_art_website_project && python manage.py migrate && gunicorn generative_art_website.wsgi --bind 0.0.0.0:$PORT"

[variables]
PYTHONUNBUFFERED = "1"
